name: raonson
description: Raonson social network v2
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path: ^1.9.0

  # UI
  cupertino_icons: ^1.0.6

  # Network
  http: ^1.2.1

  # Storage (session)
  shared_preferences: ^2.2.2

  # Media (барои қадамҳои баъдӣ)
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
