name: Build Raonson APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Java 17 (МУҲИМ)
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Create Flutter project
        run: |
          flutter create raonson
          rm -rf raonson/lib
          cp -r lib raonson/lib
          cp pubspec.yaml raonson/pubspec.yaml

      - name: Install dependencies
        run: |
          cd raonson
          flutter pub get

      - name: Clean
        run: |
          cd raonson
          flutter clean

      # ⛔ R8 OFF (ин бисёр вақт build-ро мешиканад)
      - name: Disable R8
        run: |
          echo "android.enableR8=false" >> raonson/android/gradle.properties

      - name: Build APK
        run: |
          cd raonson
          flutter build apk --release --no-shrink --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: raonson-apk
          path: raonson/build/app/outputs/flutter-apk/app-release.apk
