name: Build Raonson APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter doctor
        run: flutter doctor -v

      # 1️⃣ Сохтани Flutter project бо номи дуруст
      - name: Create Flutter project (Raonson)
        run: |
          flutter create Raonson

      # 2️⃣ Гузаронидани коди ту
      - name: Copy source code
        run: |
          rm -rf Raonson/lib
          cp -r lib Raonson/lib
          cp pubspec.yaml Raonson/pubspec.yaml

      # 3️⃣ Dependency
      - name: Get dependencies
        run: |
          cd Raonson
          flutter pub get

      # 4️⃣ Build APK
      - name: Build APK (release)
        run: |
          cd Raonson
          flutter build apk --release

      # 5️⃣ Upload
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Raonson-APK
          path: Raonson/build/app/outputs/flutter-apk/app-release.apk
