name: Build Raonson APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter doctor
        run: flutter doctor -v

      # 1️⃣ Flutter project (package name lowercase)
      - name: Create Flutter project
        run: |
          flutter create raonson

      # 2️⃣ Copy your code
      - name: Copy source code
        run: |
          rm -rf raonson/lib
          cp -r lib raonson/lib
          cp pubspec.yaml raonson/pubspec.yaml

      # 3️⃣ Get deps
      - name: Get dependencies
        run: |
          cd raonson
          flutter pub get

      # 4️⃣ Build APK
      - name: Build APK
        run: |
          cd raonson
          flutter build apk --release

      # 5️⃣ Upload
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Raonson-APK
          path: raonson/build/app/outputs/flutter-apk/app-release.apk
